# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator-Scientific.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_layoutMAIN(object):
    def setupUi(self, layoutMAIN):
        layoutMAIN.setObjectName("PowerMAx")
        layoutMAIN.setEnabled(True)
        #layoutMAIN.resize(513, 860)
        layoutMAIN.setWhatsThis("nothing!")
        layoutMAIN.setStyleSheet("")
        layoutMAIN.setDockNestingEnabled(False)
        layoutMAIN.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(layoutMAIN)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setStyleSheet("background-color:gray")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.button_About = QtWidgets.QPushButton(self.centralwidget)
        self.button_About.setStyleSheet("background-color:#505050;color:white;font:6pt Center;")
        self.button_About.setObjectName("button_About")
        self.horizontalLayout_10.addWidget(self.button_About)
        self.button_Simple = QtWidgets.QPushButton(self.centralwidget)
        self.button_Simple.setStyleSheet("background-color:#505050;color:white;font:6pt Center;")
        self.button_Simple.setObjectName("button_Simple")
        self.horizontalLayout_10.addWidget(self.button_Simple)
        self.button_Scientific = QtWidgets.QPushButton(self.centralwidget)
        self.button_Scientific.setStyleSheet("background-color:#505050;color:white;font:6pt Center;")
        self.button_Scientific.setObjectName("button_Scientific")
        self.horizontalLayout_10.addWidget(self.button_Scientific)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.text_display = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.text_display.sizePolicy().hasHeightForWidth())
        self.text_display.setSizePolicy(sizePolicy)
        self.text_display.setMinimumSize(QtCore.QSize(0, 110))
        self.text_display.setStyleSheet("background-color:#505050;color:white;font:25pt Center;")
        self.text_display.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.text_display.setObjectName("text_display")
        self.verticalLayout_2.addWidget(self.text_display, 0, QtCore.Qt.AlignTop)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.abs_value = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.abs_value.sizePolicy().hasHeightForWidth())
        self.abs_value.setSizePolicy(sizePolicy)
        self.abs_value.setMinimumSize(QtCore.QSize(70, 70))
        self.abs_value.setStyleSheet("background-color:#3C3636;font:  14pt Bold ;color: white;")
        self.abs_value.setObjectName("abs_value")
        self.horizontalLayout_9.addWidget(self.abs_value)
        self.modulo = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.modulo.sizePolicy().hasHeightForWidth())
        self.modulo.setSizePolicy(sizePolicy)
        self.modulo.setMinimumSize(QtCore.QSize(70, 70))
        self.modulo.setStyleSheet("background-color:#3C3636;font:  14pt Bold ;color: white;")
        self.modulo.setObjectName("modulo")
        self.horizontalLayout_9.addWidget(self.modulo)
        self.int_div = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.int_div.sizePolicy().hasHeightForWidth())
        self.int_div.setSizePolicy(sizePolicy)
        self.int_div.setMinimumSize(QtCore.QSize(70, 70))
        self.int_div.setStyleSheet("background-color:#3C3636;font:  14pt Bold ;color: white;")
        self.int_div.setObjectName("int_div")
        self.horizontalLayout_9.addWidget(self.int_div)
        self.factorial_button = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.factorial_button.sizePolicy().hasHeightForWidth())
        self.factorial_button.setSizePolicy(sizePolicy)
        self.factorial_button.setMinimumSize(QtCore.QSize(70, 70))
        self.factorial_button.setStyleSheet("background-color:#3C3636;font:  14pt Bold ;color: white;")
        self.factorial_button.setObjectName("factorial_button")
        self.horizontalLayout_9.addWidget(self.factorial_button)
        self.eulers_num = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.eulers_num.sizePolicy().hasHeightForWidth())
        self.eulers_num.setSizePolicy(sizePolicy)
        self.eulers_num.setMinimumSize(QtCore.QSize(70, 70))
        self.eulers_num.setStyleSheet("background-color:#3C3636;font:  14pt Bold ;color: white;")
        self.eulers_num.setObjectName("eulers_num")
        self.horizontalLayout_9.addWidget(self.eulers_num)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.sine = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.sine.sizePolicy().hasHeightForWidth())
        self.sine.setSizePolicy(sizePolicy)
        self.sine.setMinimumSize(QtCore.QSize(70, 70))
        self.sine.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sine.setStyleSheet("background-color:#3C3636;font:  14pt Bold ;color: white;")
        self.sine.setObjectName("sine")
        self.horizontalLayout_5.addWidget(self.sine)
        self.cosine = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.cosine.sizePolicy().hasHeightForWidth())
        self.cosine.setSizePolicy(sizePolicy)
        self.cosine.setMinimumSize(QtCore.QSize(70, 70))
        self.cosine.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cosine.setStyleSheet("background-color:#3C3636;font:  14pt Bold ;color: white;")
        self.cosine.setObjectName("cosine")
        self.horizontalLayout_5.addWidget(self.cosine)
        self.tangent = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tangent.sizePolicy().hasHeightForWidth())
        self.tangent.setSizePolicy(sizePolicy)
        self.tangent.setMinimumSize(QtCore.QSize(70, 70))
        self.tangent.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tangent.setStyleSheet("background-color:#3C3636;font:  14pt Bold ;color: white;")
        self.tangent.setObjectName("tangent")
        self.horizontalLayout_5.addWidget(self.tangent)
        self.cotangent = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.cotangent.sizePolicy().hasHeightForWidth())
        self.cotangent.setSizePolicy(sizePolicy)
        self.cotangent.setMinimumSize(QtCore.QSize(70, 70))
        self.cotangent.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cotangent.setStyleSheet("background-color:#3C3636;font:  14pt Bold ;color: white;")
        self.cotangent.setObjectName("cotangent")
        self.horizontalLayout_5.addWidget(self.cotangent)
        self.pi_num = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pi_num.sizePolicy().hasHeightForWidth())
        self.pi_num.setSizePolicy(sizePolicy)
        self.pi_num.setMinimumSize(QtCore.QSize(70, 70))
        self.pi_num.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pi_num.setStyleSheet("background-color:#3C3636;font:  14pt Bold ;color: white;")
        self.pi_num.setObjectName("pi_num")
        self.horizontalLayout_5.addWidget(self.pi_num)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.second_power = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.second_power.sizePolicy().hasHeightForWidth())
        self.second_power.setSizePolicy(sizePolicy)
        self.second_power.setMinimumSize(QtCore.QSize(70, 70))
        self.second_power.setStyleSheet("background-color:#3C3636;font:  14pt Bold ;color: white;")
        self.second_power.setObjectName("second_power")
        self.horizontalLayout_6.addWidget(self.second_power)
        self.third_power = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.third_power.sizePolicy().hasHeightForWidth())
        self.third_power.setSizePolicy(sizePolicy)
        self.third_power.setMinimumSize(QtCore.QSize(70, 70))
        self.third_power.setStyleSheet("background-color:#3C3636;font:  14pt Bold ;color: white;")
        self.third_power.setObjectName("third_power")
        self.horizontalLayout_6.addWidget(self.third_power)
        self.nth_power = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.nth_power.sizePolicy().hasHeightForWidth())
        self.nth_power.setSizePolicy(sizePolicy)
        self.nth_power.setMinimumSize(QtCore.QSize(70, 70))
        self.nth_power.setStyleSheet("background-color:#3C3636;font:  14pt Bold ;color: white;")
        self.nth_power.setObjectName("nth_power")
        self.horizontalLayout_6.addWidget(self.nth_power)
        self.inv_power = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.inv_power.sizePolicy().hasHeightForWidth())
        self.inv_power.setSizePolicy(sizePolicy)
        self.inv_power.setMinimumSize(QtCore.QSize(70, 70))
        self.inv_power.setStyleSheet("background-color:#3C3636;font:  14pt Bold ;color: white;")
        self.inv_power.setObjectName("inv_power")
        self.horizontalLayout_6.addWidget(self.inv_power)
        self.tens_powers = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tens_powers.sizePolicy().hasHeightForWidth())
        self.tens_powers.setSizePolicy(sizePolicy)
        self.tens_powers.setMinimumSize(QtCore.QSize(70, 70))
        self.tens_powers.setStyleSheet("background-color:#3C3636;font:  14pt Bold ;color: white;")
        self.tens_powers.setObjectName("tens_powers")
        self.horizontalLayout_6.addWidget(self.tens_powers)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.square_root = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.square_root.sizePolicy().hasHeightForWidth())
        self.square_root.setSizePolicy(sizePolicy)
        self.square_root.setMinimumSize(QtCore.QSize(70, 70))
        self.square_root.setStyleSheet("background-color:#3C3636;font:  14pt Bold ;color: white;")
        self.square_root.setObjectName("square_root")
        self.horizontalLayout_7.addWidget(self.square_root)
        self.third_root = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.third_root.sizePolicy().hasHeightForWidth())
        self.third_root.setSizePolicy(sizePolicy)
        self.third_root.setMinimumSize(QtCore.QSize(70, 70))
        self.third_root.setStyleSheet("background-color:#3C3636;font:  14pt Bold ;color: white;")
        self.third_root.setObjectName("third_root")
        self.horizontalLayout_7.addWidget(self.third_root)
        self.nth_root = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.nth_root.sizePolicy().hasHeightForWidth())
        self.nth_root.setSizePolicy(sizePolicy)
        self.nth_root.setMinimumSize(QtCore.QSize(70, 70))
        self.nth_root.setStyleSheet("background-color:#3C3636;font:  14pt Bold ;color: white;")
        self.nth_root.setObjectName("nth_root")
        self.horizontalLayout_7.addWidget(self.nth_root)
        self.log_base10 = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.log_base10.sizePolicy().hasHeightForWidth())
        self.log_base10.setSizePolicy(sizePolicy)
        self.log_base10.setMinimumSize(QtCore.QSize(70, 70))
        self.log_base10.setStyleSheet("background-color:#3C3636;font:  14pt Bold ;color: white;")
        self.log_base10.setObjectName("log_base10")
        self.horizontalLayout_7.addWidget(self.log_base10)
        self.log_basee = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.log_basee.sizePolicy().hasHeightForWidth())
        self.log_basee.setSizePolicy(sizePolicy)
        self.log_basee.setMinimumSize(QtCore.QSize(70, 70))
        self.log_basee.setStyleSheet("background-color:#3C3636;font:  14pt Bold ;color: white;")
        self.log_basee.setObjectName("log_basee")
        self.horizontalLayout_7.addWidget(self.log_basee)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.left_par = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.left_par.sizePolicy().hasHeightForWidth())
        self.left_par.setSizePolicy(sizePolicy)
        self.left_par.setMinimumSize(QtCore.QSize(70, 70))
        self.left_par.setStyleSheet("background-color:#FF9500;font:  21pt Bold ;color: white;")
        self.left_par.setObjectName("left_par")
        self.horizontalLayout_8.addWidget(self.left_par)
        self.right_par = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.right_par.sizePolicy().hasHeightForWidth())
        self.right_par.setSizePolicy(sizePolicy)
        self.right_par.setMinimumSize(QtCore.QSize(70, 70))
        self.right_par.setStyleSheet("background-color:#FF9500;font:  21pt Bold ;color: white;")
        self.right_par.setObjectName("right_par")
        self.horizontalLayout_8.addWidget(self.right_par)
        self.signs = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.signs.sizePolicy().hasHeightForWidth())
        self.signs.setSizePolicy(sizePolicy)
        self.signs.setMinimumSize(QtCore.QSize(70, 70))
        self.signs.setStyleSheet("background-color:#3C3636;font:  14pt Bold ;color: white;")
        self.signs.setObjectName("signs")
        self.horizontalLayout_8.addWidget(self.signs)
        self.percentage = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.percentage.sizePolicy().hasHeightForWidth())
        self.percentage.setSizePolicy(sizePolicy)
        self.percentage.setMinimumSize(QtCore.QSize(70, 70))
        self.percentage.setStyleSheet("background-color:#3C3636;font:  14pt Bold ;color: white;")
        self.percentage.setObjectName("percentage")
        self.horizontalLayout_8.addWidget(self.percentage)
        self.ex = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.ex.sizePolicy().hasHeightForWidth())
        self.ex.setSizePolicy(sizePolicy)
        self.ex.setMinimumSize(QtCore.QSize(70, 70))
        self.ex.setStyleSheet("background-color:#3C3636;font:  14pt Bold ;color: white;")
        self.ex.setObjectName("ex")
        self.horizontalLayout_8.addWidget(self.ex)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.button_7 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.button_7.sizePolicy().hasHeightForWidth())
        self.button_7.setSizePolicy(sizePolicy)
        self.button_7.setMinimumSize(QtCore.QSize(70, 70))
        self.button_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_7.setStyleSheet("background-color:white;font:  21pt Bold ;color: black;")
        self.button_7.setObjectName("button_7")
        self.horizontalLayout_4.addWidget(self.button_7)
        self.button_8 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.button_8.sizePolicy().hasHeightForWidth())
        self.button_8.setSizePolicy(sizePolicy)
        self.button_8.setMinimumSize(QtCore.QSize(70, 70))
        self.button_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_8.setStyleSheet("background-color:white;font:  21pt Bold ;color: black;")
        self.button_8.setObjectName("button_8")
        self.horizontalLayout_4.addWidget(self.button_8)
        self.button_9 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.button_9.sizePolicy().hasHeightForWidth())
        self.button_9.setSizePolicy(sizePolicy)
        self.button_9.setMinimumSize(QtCore.QSize(70, 70))
        self.button_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_9.setStyleSheet("background-color:white;font:  21pt Bold ;color: black;")
        self.button_9.setObjectName("button_9")
        self.horizontalLayout_4.addWidget(self.button_9)
        self.delete_one = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.delete_one.sizePolicy().hasHeightForWidth())
        self.delete_one.setSizePolicy(sizePolicy)
        self.delete_one.setMinimumSize(QtCore.QSize(70, 70))
        self.delete_one.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_one.setStyleSheet("background-color:red;font:  16pt Bold ;color: white;")
        self.delete_one.setObjectName("delete_one")
        self.horizontalLayout_4.addWidget(self.delete_one)
        self.delete_all = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.delete_all.sizePolicy().hasHeightForWidth())
        self.delete_all.setSizePolicy(sizePolicy)
        self.delete_all.setMinimumSize(QtCore.QSize(70, 70))
        self.delete_all.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_all.setStyleSheet("background-color:red;font:  16pt Bold ;color: white;")
        self.delete_all.setObjectName("delete_all")
        self.horizontalLayout_4.addWidget(self.delete_all)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.button_4 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.button_4.sizePolicy().hasHeightForWidth())
        self.button_4.setSizePolicy(sizePolicy)
        self.button_4.setMinimumSize(QtCore.QSize(70, 70))
        self.button_4.setStyleSheet("background-color:white;font:  21pt Bold ;color: black;")
        self.button_4.setObjectName("button_4")
        self.horizontalLayout_3.addWidget(self.button_4)
        self.button_5 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.button_5.sizePolicy().hasHeightForWidth())
        self.button_5.setSizePolicy(sizePolicy)
        self.button_5.setMinimumSize(QtCore.QSize(70, 70))
        self.button_5.setStyleSheet("background-color:white;font:  21pt Bold ;color: black;")
        self.button_5.setObjectName("button_5")
        self.horizontalLayout_3.addWidget(self.button_5)
        self.button_6 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.button_6.sizePolicy().hasHeightForWidth())
        self.button_6.setSizePolicy(sizePolicy)
        self.button_6.setMinimumSize(QtCore.QSize(70, 70))
        self.button_6.setStyleSheet("background-color:white;font:  21pt Bold ;color: black;")
        self.button_6.setObjectName("button_6")
        self.horizontalLayout_3.addWidget(self.button_6)
        self.sub = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.sub.sizePolicy().hasHeightForWidth())
        self.sub.setSizePolicy(sizePolicy)
        self.sub.setMinimumSize(QtCore.QSize(70, 70))
        self.sub.setStyleSheet("background-color:#FF9500;font:  21pt Bold ;color: white;")
        self.sub.setObjectName("sub")
        self.horizontalLayout_3.addWidget(self.sub)
        self.div = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.div.sizePolicy().hasHeightForWidth())
        self.div.setSizePolicy(sizePolicy)
        self.div.setMinimumSize(QtCore.QSize(70, 70))
        self.div.setStyleSheet("background-color:#FF9500;font:  21pt Bold ;color: white;")
        self.div.setObjectName("div")
        self.horizontalLayout_3.addWidget(self.div)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.button_1 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.button_1.sizePolicy().hasHeightForWidth())
        self.button_1.setSizePolicy(sizePolicy)
        self.button_1.setMinimumSize(QtCore.QSize(70, 70))
        self.button_1.setStyleSheet("background-color:white;font:  21pt Bold ;color: black;")
        self.button_1.setObjectName("button_1")
        self.horizontalLayout_2.addWidget(self.button_1)
        self.button_2 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.button_2.sizePolicy().hasHeightForWidth())
        self.button_2.setSizePolicy(sizePolicy)
        self.button_2.setMinimumSize(QtCore.QSize(70, 70))
        self.button_2.setStyleSheet("background-color:white;font:  21pt Bold ;color: black;")
        self.button_2.setObjectName("button_2")
        self.horizontalLayout_2.addWidget(self.button_2)
        self.button_3 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.button_3.sizePolicy().hasHeightForWidth())
        self.button_3.setSizePolicy(sizePolicy)
        self.button_3.setMinimumSize(QtCore.QSize(70, 70))
        self.button_3.setStyleSheet("background-color:white;font:  21pt Bold ;color: black;")
        self.button_3.setObjectName("button_3")
        self.horizontalLayout_2.addWidget(self.button_3)
        self.add = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.add.sizePolicy().hasHeightForWidth())
        self.add.setSizePolicy(sizePolicy)
        self.add.setMinimumSize(QtCore.QSize(70, 70))
        self.add.setStyleSheet("background-color:#FF9500;font:  21pt Bold ;color: white;")
        self.add.setObjectName("add")
        self.horizontalLayout_2.addWidget(self.add)
        self.mul = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.mul.sizePolicy().hasHeightForWidth())
        self.mul.setSizePolicy(sizePolicy)
        self.mul.setMinimumSize(QtCore.QSize(70, 70))
        self.mul.setStyleSheet("background-color:#FF9500;font:  21pt Bold ;color: white;")
        self.mul.setObjectName("mul")
        self.horizontalLayout_2.addWidget(self.mul)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_0 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.button_0.sizePolicy().hasHeightForWidth())
        self.button_0.setSizePolicy(sizePolicy)
        self.button_0.setMinimumSize(QtCore.QSize(70, 70))
        self.button_0.setStyleSheet("background-color:white;font:  21pt Bold ;color: black;")
        self.button_0.setObjectName("button_0")
        self.horizontalLayout.addWidget(self.button_0)
        self.point = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.point.sizePolicy().hasHeightForWidth())
        self.point.setSizePolicy(sizePolicy)
        self.point.setMinimumSize(QtCore.QSize(70, 70))
        self.point.setStyleSheet("background-color:white;font:  21pt Bold ;color: black;")
        self.point.setObjectName("point")
        self.horizontalLayout.addWidget(self.point)
        self.exp = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.exp.sizePolicy().hasHeightForWidth())
        self.exp.setSizePolicy(sizePolicy)
        self.exp.setMinimumSize(QtCore.QSize(70, 70))
        self.exp.setStyleSheet("background-color:white;font:  21pt Bold ;color: black;")
        self.exp.setObjectName("exp")
        self.horizontalLayout.addWidget(self.exp)
        self.equal = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.equal.sizePolicy().hasHeightForWidth())
        self.equal.setSizePolicy(sizePolicy)
        self.equal.setMinimumSize(QtCore.QSize(140, 70))
        self.equal.setAutoFillBackground(False)
        self.equal.setStyleSheet("background-color:#FF9500;font:  21pt Bold ;color: white;")
        self.equal.setShortcut("")
        self.equal.setCheckable(False)
        self.equal.setChecked(False)
        self.equal.setAutoRepeat(False)
        self.equal.setAutoExclusive(False)
        self.equal.setAutoDefault(False)
        self.equal.setDefault(False)
        self.equal.setFlat(False)
        self.equal.setObjectName("equal")
        self.horizontalLayout.addWidget(self.equal)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2.addWidget(self.frame)
        layoutMAIN.setCentralWidget(self.centralwidget)

        self.retranslateUi(layoutMAIN)
        QtCore.QMetaObject.connectSlotsByName(layoutMAIN)

    def retranslateUi(self, layoutMAIN):
        _translate = QtCore.QCoreApplication.translate
        layoutMAIN.setWindowTitle(_translate("layoutMAIN", "MainWindow"))
        self.button_About.setText(_translate("layoutMAIN", "About us!"))
        self.button_Simple.setText(_translate("layoutMAIN", "Simple"))
        self.button_Scientific.setText(_translate("layoutMAIN", "Scientific"))
        self.text_display.setText(_translate("layoutMAIN", "0"))
        self.abs_value.setText(_translate("layoutMAIN", "abs"))
        self.modulo.setText(_translate("layoutMAIN", "modulo"))
        self.int_div.setText(_translate("layoutMAIN", "div"))
        self.factorial_button.setText(_translate("layoutMAIN", "x!"))
        self.eulers_num.setText(_translate("layoutMAIN", "e"))
        self.sine.setText(_translate("layoutMAIN", "sin"))
        self.cosine.setText(_translate("layoutMAIN", "cos"))
        self.tangent.setText(_translate("layoutMAIN", "tan"))
        self.cotangent.setText(_translate("layoutMAIN", "cot"))
        self.pi_num.setText(_translate("layoutMAIN", "π"))
        self.second_power.setText(_translate("layoutMAIN", "xu00B2"))
        self.third_power.setText(_translate("layoutMAIN", "xu00B3"))
        self.nth_power.setText(_translate("layoutMAIN", "x^n"))
        self.inv_power.setText(_translate("layoutMAIN", "xu207bxb9"))
        self.tens_powers.setText(_translate("layoutMAIN", "10^x"))
        self.square_root.setText(_translate("layoutMAIN", "u00B2u221A"))
        self.third_root.setText(_translate("layoutMAIN", "u00B3u221A"))
        self.nth_root.setText(_translate("layoutMAIN", "u221A"))
        self.log_base10.setText(_translate("layoutMAIN", "logu2081u2080"))
        self.log_basee.setText(_translate("layoutMAIN", "ln"))
        self.left_par.setText(_translate("layoutMAIN", "("))
        self.right_par.setText(_translate("layoutMAIN", ")"))
        self.signs.setText(_translate("layoutMAIN", "u00B1"))
        self.percentage.setText(_translate("layoutMAIN", "%"))
        self.ex.setText(_translate("layoutMAIN", "e^x"))
        self.button_7.setText(_translate("layoutMAIN", "7"))
        self.button_8.setText(_translate("layoutMAIN", "8"))
        self.button_9.setText(_translate("layoutMAIN", "9"))
        self.delete_one.setText(_translate("layoutMAIN", "DEL"))
        self.delete_all.setText(_translate("layoutMAIN", "AC"))
        self.button_4.setText(_translate("layoutMAIN", "4"))
        self.button_5.setText(_translate("layoutMAIN", "5"))
        self.button_6.setText(_translate("layoutMAIN", "6"))
        self.sub.setText(_translate("layoutMAIN", "-"))
        self.div.setText(_translate("layoutMAIN", "/"))
        self.button_1.setText(_translate("layoutMAIN", "1"))
        self.button_2.setText(_translate("layoutMAIN", "2"))
        self.button_3.setText(_translate("layoutMAIN", "3"))
        self.add.setText(_translate("layoutMAIN", "+"))
        self.mul.setText(_translate("layoutMAIN", "x"))
        self.button_0.setText(_translate("layoutMAIN", "0"))
        self.point.setText(_translate("layoutMAIN", "."))
        self.exp.setText(_translate("layoutMAIN", "EXP"))
        self.equal.setText(_translate("layoutMAIN", "="))

